---
title: "Petroleum Based Diesel Fuel Price in the U.S"
---

-   Source: the [U.S. Energy Information Administration(EIA)](https://www.eia.gov/opendata/){target="_blank"}

```{r packages, echo = F, message = FALSE, warning = FALSE}
devnull <- sapply(c("httr2", "jsonlite", "tidyverse"), library, character.only = TRUE)
api_key <- Sys.getenv("API_KEY")
```

## Sourcing Petroleum Based Diesel Fuel Price in the U.S from the EIA resource.  

```{r PetrodDieselUSPrice, echo = T, message = FALSE, warning=FALSE, results='asis', fig.width= 14, fig.height= 8}
eia_url <- "https://api.eia.gov/v2/"


historical_diesel_prices <- request(paste0(eia_url, "petroleum/pri/gnd/data/")) %>%
  req_url_query(
    `api_key` = api_key,
    `frequency` = "weekly",
    `data[0]` = "value",
    `facets[series][]` = "EMD_EPD2D_PTE_NUS_DPG", 
    `sort[0][column]` = "period",
    `sort[0][direction]` = "desc",
    `length` = 5000
  ) %>%
  req_perform() %>%
  resp_body_json()

price_df <- do.call(rbind, lapply(historical_diesel_prices$response$data, as.data.frame))

price_df$period <- ymd(price_df$period)

price_df$value <- as.numeric(price_df$value)

price_df <- price_df %>%
  filter(year(period) > 2000)


ggplot(price_df, aes(x = period, y = value, group = 1)) +
  geom_line(color = "steelblue", linewidth = 1) +
  geom_point(color = "steelblue", size = 2) +
  theme_minimal() + 
  ylab("$/GAL") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        title = element_text(size = 14, face = "bold"),
        plot.caption = element_text(size = 12)) +
  labs(
    title = "Petroleum based Diesel Price Over Time in the US since 2000",
    x = "Time",
    y = "$/GAL",
    caption = "Source: U.S. Energy Information Administration (EIA), https://www.eia.gov/") +
  # Set X-axis major grid to 1 month intervals
  scale_x_date(date_breaks = "1 year", date_minor_breaks = "1 month", date_labels = "%Y") +
  scale_y_continuous(breaks = seq(0, 10, by = 0.25)) 
```


